[package]
name = "fittings-server"
version = "0.1.0"
authors = ["Cameron Milsom <cameron.milsom@gmail.com>"]
repository = "https://github.com/Fittings/fittings-site"

[dependencies]
rocket = "0.2.2"
rocket_codegen = "0.2.2"
