[development]
address = "localhost"
port = 8000
log = "normal"

[staging]
address = "localhost"
port = 8008
log = "normal"

[production]
address = "localhost"
port = 8088
log = "critical"
